Auto select song book if theres only 1 songbook
Church-Life-Apps/Songs pull request #163
Opened 2022-04-05 02:36 UTC by brandonxia01

The "choose a song book" page is kind of a useless step if theres only 1 book. Putting this in place, and it will auto update when Red Book gets finished.

2022-04-05 02:56 UTC, 123asian requested changes
Since you got rid of line 43, defaultNavigationTitle isn't used anywhere, so we can probably remove the import in line 2

2022-04-05 02:59 UTC, MiTo0o commented on src/pages/HomePage.tsx
> +      if (books.length == 1) {
is this meant to be ==?

2022-04-05 03:08 UTC, brandonxia01 commented on src/pages/HomePage.tsx
> +      if (books.length == 1) {
mm probably `===` is right, ty

2022-04-05 03:09 UTC, brandonxia01 commented
> Since you got rid of line 43, defaultNavigationTitle isn't used anywhere, so we can probably remove the import in line 2

Good catch

2022-04-06 07:01 UTC, brandonxia01 commented
@123asian @MiTo0o can you re review

2022-04-07 04:00 UTC, brotatotes approved these changes

2022-04-07 04:58 UTC, merged