temporary "fix" for the search bar issue
Church-Life-Apps/Songs pull request #92
Opened 2021-01-03 23:54 UTC by nubwett

added a very inefficient way to solve the issue by using a time interval to check if the database is loaded or not

2021-01-04 00:19 UTC, brotatotes requested changes

2021-01-04 00:19 UTC, brotatotes commented on src/pages/BookPage.tsx
> +  // const [showSearchBar, setShowSearchBar] = useState<boolean>(DbManager.isInitialized());
remove this and other commented lines of code

2021-01-04 00:19 UTC, brotatotes commented on src/pages/BookPage.tsx
> +  const check = setInterval(checkDatabaseLoad, 1000);
This seems very hacky. Is there another way?

2021-01-05 01:30 UTC, brandonxia01 reviewed
Thanks for the PR! 

Maybe you can give this a try? - The DB finishes initialization on this line https://github.com/Church-Life-Apps/Songs/blob/master/src/database/DbManager.tsx#L57, so if we can trigger a re-render of the search bar or set `hidden=false` when that code block runs then we will only need to do it once!

2021-01-16 02:37 UTC, brotatotes commented
Opening new PR #93

2021-01-16 02:37 UTC, closed without merging